### ISSUE TITLE
hit@k and mini rank Obtain whether the mean, maximum or something else.

### ISSUE THREAD

**Issue by NicoleLia** [zqypku/mm_poison#4]
Hi all,
In your paper, you use hit@K and mini rank to evaluate poisoning effects. **I would like to know whether you obtained the mean value of 10 epochs or the best result or some others way.**
When I reproduce the code, my configuration was already consistent with your original paper, but for COCO attacks such as boat2dog, the best result I got was {hit1,5,10,mini_rank: 0.02, 0.288, 0.628, 13.284}, and the mean value was {hit1,5,10,mini_rank: 0.0124, 0.1908, 0.4664, 16.16}. This is a bit different from the original paper {hit1,5,10,mini_rank: 0.012, 0.212, 0.516, 15.280}.

**Comment by zqypku** [comment]
Hi,

Thank you for your interest in our work.

Regarding your question, in the paper, we reported the results of 10 epochs rather than just the best result. We believe this provides a more robust view of the attack’s performance by accounting for potential fluctuations across epochs. Additionally, the configuration used in the paper is not necessarily optimized for the attack, so we encourage exploring other configurations to see if performance can be improved.

Looking at the numbers you obtained, **the differences are minimal, which is expected**. Variations can arise from factors like random initialization, minor data preprocessing differences, or hardware specifics. These small differences should not affect the overall conclusions of the experiment.

If you're using the same configuration as described in the paper, you're on the right track, and the variations you're seeing are within an acceptable margin. Feel free to reach out if you have further questions or need more insights!
